In [20]:
import numpy as np 

In [21]:
s = np.array(5)
print(s.ndim)
print(s.shape)
print("========")
 
v = np.array([1,2,3,4,5,6])
print(v.ndim)
print(v.shape)
print("========")
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m.ndim)
print(m.shape)

0
()
1
(6,)
2
(3, 3)


In [22]:
def array_reshape(arr: list, rows:int, cols:int):

    try:
        arr =np.array(arr)
        return arr.reshape(rows.cols)
    except(TypeError,ValueError) as e:
        raise ValueError(f"Invalid reshape operation:{e}")

In [23]:
vec = [1,2,3,4,5,6]
vec

[1, 2, 3, 4, 5, 6]

In [24]:
m = np.array([[1,2,3],
              [4,5.5,6],
              [7,8,9]])
print(m.dtype)
print(m)

float64
[[1.  2.  3. ]
 [4.  5.5 6. ]
 [7.  8.  9. ]]


In [25]:
m = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
fmat = m.astype(float)
fmat

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [26]:
m = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
v = np.array([3,2,1,5])
m[1,2]


np.str_('6')

In [27]:
m = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
v = np.array([3,2,1,5])
m[-3:-1 , -3:-1]


array([['1', '2'],
       ['4', '5']], dtype='<U21')

In [28]:
mat = np.array([[1,2,'3'],
              [4,5,6],
              [7,8,9]])
matT= mat.T
matT

array([['1', '4', '7'],
       ['2', '5', '8'],
       ['3', '6', '9']], dtype='<U21')

In [29]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])